#include <iostream>
#include <thread>
#include <mutex>
#include <chrono>
#include<list>
#include<string>

using namespace std;

int main()
{
    list<int> numbers;
    for(int i = 1; i < 100; ++i) numbers.push_back(i);
    int count = 0;



    /*
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Testing numbers...
    Finished!
    */

    cout << "Result: " << count << endl; // Result: 19
    return 0;
}
